config/routes.rb
Shopos::Application.routes.draw do

  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "register" => "users#new"
  match "about" => "meta#about"
  resources :user_sessions

  resources :users

  root :controller => :shops,:action=>:index
  resources :shops

  resources :categories do
    resources :shops
  end

end

app/models/shop.rb
# coding: utf-8

class Shop < ActiveRecord::Base
  validates_presence_of :posname, :realname, :message=>"不能为空"
  #validates_uniqueness_of :posname, :realname, :case_sensitive => false, :message=>"已经有相同的名字存在了,请检查是否重复添加"
  validates_uniqueness_of :realname, :case_sensitive => false, :message=>"已经有相同的名字存在了,请检查是否重复添加"
  belongs_to :category
  self.per_page = 3


#  def to_param
#    "#{id}-#{realname.parameterize}"
#  end

end

app/controllers/shops_controller.rb
# coding: utf-8

class ShopsController < ApplicationController

  before_filter :authenticate, :only => [:destroy]
  before_filter :require_user_login, :only => [:edit, :update]

  # GET /shops
  # GET /shops.xml
  def index
    if params[:search]
      set_seo_meta('包含 ' + params[:search] + ' 的搜索结果', '包含' + params[:search] + '的eftpos名字')
      @shops = Shop.find(:all, :conditions => ['UPPER(posname) like ? or UPPER(realname) like ?',"%#{params[:search].upcase}%","%#{params[:search].upcase}%"]).paginate :page => params[:page], :per_page =>10
    else
      @shops = Shop.all.paginate :page => params[:page], :per_page => 10
      set_seo_meta('所有商店')
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @shops }
      end
    end
  end

  # GET /shops/1
  # GET /shops/1.xml
  def show 
    @shop = Shop.find(params[:id])
    set_seo_meta(@shop.realname + ' &raquo; ' + @shop.posname, @shop.realname + ' '+ @shop.posname)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.xml
  def new
    @shop = Shop.new
    set_seo_meta('添加新商店')
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
    set_seo_meta('编辑 &raquo; ' + @shop.realname + ' &raquo; ' + @shop.posname, @shop.realname + ' '+ @shop.posname)
  end

  # POST /shops
  # POST /shops.xml
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to(@shop, :notice => "商店添加成功") }
        format.xml  { render :xml => @shop, :status => :created, :location => @shop }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.xml
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to(@shop, :success => "商店更新成功") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.xml
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to(shops_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation" class="error">
      <h2>请修正下面<%= @shop.errors.count %>处问题:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mandatory">
    <div class="field">
      <%= f.label "eftPOS名字" %>
      <%= f.text_field :posname %>
    </div>
    <div class="field">
      <%= f.label "商店名字" %>
      <%= f.text_field :realname %>
    </div>
    <div class="field">
    <%= f.label "类别" %>
    <%= select(:shop,"category_id", Category.all.collect {|c| [c.name, c.id] }) %>
    </div>
    <div class="non-mandatoryInfo">
      <a href="#">输入其他信息</a>
    </div>
  <div class="non-mandatory">  
    <div class="field">
      <%= f.label "电话" %>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label "地址" %>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label "其他信息" %>
      <%= f.text_area :other, :rows => "3" %>
    </div>
  </div>
  <div class="actions">
      <%= f.submit :value => "写好了,加上去" %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>编辑商店</h1>

<%= render 'form' %>

<%= link_to '回到商店', @shop %> |
<%= link_to '回到首页', shops_path %>

app/views/shops/index.html.erb
<div class="title">
  <% if params[:search] != nil && params[:search] != '' %>
    <h1>包含 <%= params[:search]%> 的搜索结果</h1>
  <% else %>
    <h1>所有商店</h1>
    <%= link_to '添加新商店', new_shop_path %>
  <% end %>
</div>
<% if @shops.length == 0 %>
  <span class="searchResults">没有找到您要找的,帮助我们<%= link_to '添加这个商店', new_shop_path %></span>
  <% else %>
<table class="searchResults">
  <tr>
    <th>商店名字</th>
    <th>eftpos 名字</th>
    <th>电话</th>
    <th>地址</th>
    <th>分类</th>
    <th></th>
    <th></th>
  </tr>

<% @shops.each do |shop| %>
  <tr>
    <td><%= link_to shop.realname, shop %></td>
    <td><%= shop.posname %></td>
    <td><%= shop.phone %></td>
    <td><%= shop.address %></td>
    <td class="tdmisc"><%= shop.category.name %></td>
    <% if current_user %>
      <td class="tdmisc"><%= link_to '编辑', edit_shop_path(shop) %></td>
    <% else %>
      <td> </td>
    <% end %>
    <% if current_user && current_user.username == 'shawn' %>
      <td class="tdmisc"><%= link_to '删除', shop, :confirm => 'Are you sure?', :method => :delete %></td>
    <% else %>
      <td> </td>
    <% end %>
  </tr>
<% end %>
</table>
 <%= will_paginate @shops %>
<% end %>
<br />

app/views/shops/new.html.erb
<h1>添加新商店</h1>

<%= render 'form' %>

<%= link_to '回到首页', shops_path %>

app/views/shops/show.html.erb
<%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true", "maps.js" %>
<script type="text/javascript">
$(document).ready(function() {
    initialize("<%= @shop.address %>");
    codeAddress("<%= @shop.address %>");
});
</script>
<div>
<table id="details">
  <tbody>
    <tr>
      <td class="meta">商店名字</td>
      <td><%= @shop.realname %></td>
    </tr>
    <tr>
      <td class="meta">eftpos名字</td>
      <td><%= @shop.posname %></td>
    </tr>
    <tr>
      <td class="meta">类别</td>
      <td><%= @shop.category.name %></td>
    </tr>
    <tr>
      <td class="meta">电话</td>
      <td><%= @shop.phone %></td>
    </tr>
    <tr>
      <td class="meta">地址</td>
      <td><%= @shop.address %></td>
    </tr>
    <tr>
      <td class="meta">其他信息</td>
      <td><%= @shop.other %></td>
    </tr>
  </tbody>
</table>
<div id="map_canvas">

</div>
</div>
<div>
<% if current_user %>
  <%= link_to '编辑', edit_shop_path(@shop) %> |
<% else %>
  <%= link_to '登陆', login_path %>后可以编辑这个商店 |
<% end %>
<%= link_to '回到首页', shops_path %>
</div>