config/routes.rb
Shopos::Application.routes.draw do

  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "register" => "users#new"
  match "about" => "meta#about"
  resources :user_sessions

  resources :users

  root :controller => :shops,:action=>:index
  resources :shops

  resources :categories do
    resources :shops
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= raw @page_title %></title>
  <meta name="keywords" content="<%= @meta_keywords %>" />
  <meta name="description" content="<%= @meta_description %>" />
  <%= stylesheet_link_tag :flutie, :cache => false %>
  <!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>-->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19521910-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  </script>
</head>
<body>
  <div id="wrapper">
    <div class="header">
        <h1 class="logo">
          <a href="/" title="eftpos"></a>
        </h1>
        <div class="login">
          <% if current_user %>
            <%= link_to "我的资料", edit_user_path(:current) %> | 
            <%= link_to "登出", logout_path %>
          <% else %>
            <%= link_to "注册", register_url %> |
            <%= link_to "登录", login_path %>
          <% end %>
        </div>
      <div id="nav_search" style="float:right">
        <form action="/shops" method="get">
          <input type="text" name="search" value="" id="search" />
          <button type="submit">搜索</button>
        </form>
      </div>
    </div>
    <% if notice %>
      <div class="success"><%= notice %></div>
    <% end %>
    <div class="content">
        <%= yield %>
    </div>
    <div class="footer">
      <span>Created by <a href="http://shawnjiang.com">Shawn</a> &copy; 2010 | <%= link_to "关于本站", about_path %></span>
    </div>
  </div>
</body>
</html>